baseURL: https://cmna-workshop.github.io/cmna24
languageCode: en-gb
title: CMNA'24
theme: PaperModX
publishDir: docs
params:
  description: "Theme PaperModX - https://github.com/reorx/hugo-PaperModX"
  author:
    - Simon
  homeInfoParams:
    Title: "The 24th International Workshop on Computational Models of Natural Argument (CMNA'24)"
    Content: |
        The forthcoming 24th Edition of the Workshop on Computational Models of Natural Argument (CMNA'24) will be held as part of the <a href="https://comma2024.krportal.org/" style="text-decoration:underline">10th International Conference on Computational Models of Argument</a> (COMMA 2024).

        To celebrate our co-location with COMMA, this year we solicit contributions on the special theme of "**domains of natural argument**". Contributions to this theme will form the focus of a subsequent, post-workshop, special issue of the <a href="https://www.iospress.com/catalog/journals/argument-computation" style="text-decoration:underline">Journal of Argument & Computation</a>. 

        The special theme should be interpreted broadly, to reflect the wide range of argumentative practices in specialist domains such as law, medicine, natural sciences, economics, sociology, education, public policy, behaviour change, explainable AI, military intelligence, software engineering, implementation science, business and financial communication, etc. 
        
        Additionally contributions within this theme might explore various questions: 
        - What features (e.g., dialogue models, argumentation schemes, speech acts, rhetorical devices and/or linguistic cues) are particular to a given domain. 
        - How do they relate to features of other specialist domains or "everyday" argumentation? 
        - How can study of natural argument in a particular domain inform models of natural argument in other domains? 
        - How are classical models of natural argument and domain-specific models related to each other?

        Finally, we also solicit papers concerned with the full range of <a href="topics/" style="text-decoration:underline">topics</a> that CMNA usually focusses upon.

  defaultTheme: auto
  ShowPostNavLinks: true
  #ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: News
          url: /news/
          weight: 1
        - name: Topics
          url: /topics/
          weight: 1
        - name: Submission
          url: /submission/
          weight: 4
        - name: Dates
          url: /dates/
          weight: 5
        - name: Organisation
          url: /organisation/
          weight: 10
        - name: Programme
          url: /programme/
          weight: 12
        - name: About
          url: /about/
          weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
