baseURL: https://cmna-workshop.github.io/cmna24
languageCode: en-gb
title: CMNA'24
theme: PaperModX
publishDir: docs
params:
  description: "Theme PaperModX - https://github.com/reorx/hugo-PaperModX"
  author:
    - Simon
  homeInfoParams:
    Title: "The 24th International Workshop on Computational Models of Natural Argument (CMNA'24)"
    Content: |
        Since its inception in 2001, the CMNA workshop series has focused upon the issue of modelling “*natural*” argumentation, where naturalness may range across a variety of forms, perhaps involving the use of visual rather than linguistic means to illustrate a point, for example using graphics or multimedia, or applying more sophisticated rhetorical devices, interacting at various layers of abstraction, or exploiting "extra-rational" characteristics of the audience, taking into account emotions and affective factors.
        
        AI has witnessed a prodigious growth in uses of argumentation throughout many of its subdisciplines: 
        - agent system negotiation protocols that demonstrate higher levels of sophistication and robustness; 
        - argumentation-based models of evidential relations and legal processes that are more expressive; 
        - groupwork tools that use argument to structure interaction and debate; 
        - computer-based learning tools that exploit monological and dialogical argument structures in designing pedagogic environments; 
        - decision support systems that build upon argumentation theoretic models of deliberation to better integrate with human reasoning; 
        - and models of knowledge engineering structured around core concepts of argument to simplify knowledge elicitation and representation problems. 

        Furthermore, benefits have not been unilateral for AI, as demonstrated by the increasing presence of AI scholars in classical argumentation theory events and journals, and AI implementations of argument finding application in both research and pedagogic practice within philosophy and argumentation theory. 

  defaultTheme: auto
  ShowPostNavLinks: true
  #ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: News
          url: /news/
          weight: 1
        - name: Topics
          url: /topics/
          weight: 1
        - name: Submission
          url: /submission/
          weight: 4
        - name: Dates
          url: /dates/
          weight: 5
        - name: Organisation
          url: /organisation/
          weight: 10
        - name: Programme
          url: /programme/
          weight: 12

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
